spring.application.name=demo
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/delivery_db?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=springuser
spring.datasource.password=springpass

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# ← ADD THESE TWO LINES
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true